### ISSUE TITLE
Choosing empty string first when confronted with repeating elements?

### ISSUE THREAD

**Issue by ddooley** [fent/randexp.js#105]
Would there be a way to add a flag to always choose the minimal string first when working on strings containing repeating elements * + ?
I tried "randexp.max = 0;" but that still lets a character in, e.g. \d* yields a number, on first iteration it seems, not an empty string.

Thanks,

**Comment by fent** [comment]
I tried this quick test, and it prints an empty string for all iterations

```js
let re = new RandExp('\\d*');
re.max = 0;
for (let i = 0; i < 10; i++) {
  console.log(re.gen());
}
```

are you doing something similar?

**Comment by ddooley** [comment]
Ah - you are so right.  I got tricked by the iterator.  First value was the minimal one.  Sorry for the bother.

**Comment by ddooley** [comment]
Um, I'm back.  It wasn't an iterator thing, but possibly something that isn't achievable. I have this to generate a decimal # 1.XXXX...

 (1\\.(0|\\d+))

I was hoping to get it to generate 1.0 first, then 1.???... afterwards.  This means rather than a random selection of the "|" separator list parts, I'd want a deterministic algorithm that chooses the first option, then the remaining ones.  Is there any ways to accomplish that?  Faint hope!

**Comment by fent** [comment]
look at https://www.npmjs.com/package/genex

**Comment by ddooley** [comment]
Cool, thanks so much!
