### ISSUE TITLE
restrictions on supplied regular expressions

### ISSUE THREAD

**Issue by Unrealman1** [fent/randexp.js#107]
I am trying to generate a string using following [regExp](https://regex101.com/r/GtGrZ8/2)
`js
  new RandExp(/^(?=.*[a-zа-я])(?=.*[A-ZА-Я])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,16})/).gen()
`
Above regExp generates empty string locally and way longer string then required on [ your web](http://fent.github.io/randexp.js/#r=%5E%28%3F%3D.*%5Ba-z%u0430-%u044F%5D%29%28%3F%3D.*%5BA-Z%u0410-%u042F%5D%29%28%3F%3D.*%5B0-9%5D%29%28%3F%3D.*%5B%21@%23%5C%24%25%5C%5E%26%5C*%5D%29%28%3F%3D.%7B8%2C16%7D%29&i).
I guess culprit is "(?=.{8,16})"
So what are restriction on supplied regular expressions

**Comment by fent** [comment]
could have to do with some characters not being included in the [defaultRange](https://github.com/fent/randexp.js#default-range)

there's more discussion, and a debate, about it in this issue: https://github.com/fent/randexp.js/issues/93

**Comment by fent** [comment]
and the website hasn't been updated with these changes in around 2 years. will look into updating it soon.

**Comment by Unrealman1** [comment]
@fent same behavior can be reproduced with only defautRange 
`/(?=.*[a-z])(?=.{8,16})/ `  calling "gen()" results in empty string

**Comment by fent** [comment]
oh.. lookaheads are currently ignored. see https://github.com/fent/randexp.js/issues/18
