### ISSUE TITLE
Probability control

### ISSUE THREAD

**Issue by Philosoph228** [fent/randexp.js#112]
Hi! I have chained sequence like:
`пр(ив(ет(ик(и)?|cтвую(( дорогой)? друг)?)?)?)?`

And I want equal chance of each possible variant.
It seems because it's chainly folded each into another, I have got this: `пр` will have 50% chance, `прив` — 25%, `привет` — 12.5% and so on.
But I wish they all had same chance.

How would I solve it? Is there any chance control, or somewhat what should I do to achieve desired effect?

**Comment by fent** [comment]
we could add new syntax like `np(?[25%]et)?` but then it wouldn't really be regex syntax. this may be out of the scope of this project
