### ISSUE TITLE
Use proper random numbers by default.

### ISSUE THREAD

**Issue by lgarron** [fent/randexp.js#16]
I wrote a [`randomInt` package](https://github.com/lgarron/randomInt.js) for this when I needed it once.

Using it should be as simple as replacing the definition of `RandExp.prototype.randInt` with:

    return a + randomInt.below(b + 1 - a);

**Comment by michaelficarra** [comment]
What benefit would this have? The current version is similarly terse, clearly correct, and only written in one place.

**Comment by georgePadolsey** [comment]
mhm, I mean it seems like something the programmer should use dependent on the project. Math.random is sufficiently random for this kind of project. The reason why more unpredictable pseudo-random number generators exist is to make it very hard to predict the next output from the generator which is useful in security. Math.random may be predictable [at some level] however it still appears random for everyday use and this is everyday use. -- That is unless you need to generate regex's for the NSA and then you can just easily replace the RandExp#randInt method yourself ;)

**Comment by lgarron** [comment]
I believe I saw people on Hacker News mentioning/linking to use cases that use this as a random generator for identifiers.

> Math.random is sufficiently random for this kind of project.
That's only true until it isn't. ;-)

Using good random numbers should also be efficient enough for these use cases, although I suppose I understand the argument that the code should be simple and standalone.
