### ISSUE TITLE
Math.random() is not

### ISSUE THREAD

**Issue by tomByrer** [fent/randexp.js#21]
Shouldn't use built in JS Math.random() since it will repeat itself; too dangerous to use for 'Unique ID' etc.
https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d#.uskhjv9vc

**Comment by fent** [comment]
https://github.com/fent/randexp.js#custom-prng

**Comment by tomByrer** [comment]
Reading sometimes is not my strength ;)
cheers

**Comment by tomByrer** [comment]
Might not matter too much soon; v8 will use xorshift128+.
http://v8project.blogspot.com/2015/12/theres-mathrandom-and-then-theres.html
