### ISSUE TITLE
readme extend: usage, json-schema-faker

### ISSUE THREAD

**Issue by ducin** [fent/randexp.js#23]
Hello,

First of all, thank you for your work on randexp.js!

I'm a co-author of [JSON-Schema faker](https://github.com/json-schema-faker/json-schema-faker), a mock data generator that parses JSON schema files and generates random domain data, basing on few libraries... including randexp.js :) I would like to ask if I can extend the readme with a mention about [JSON-Schema faker](https://github.com/json-schema-faker/json-schema-faker) - would you accept such PR?

**Comment by fent** [comment]
Yeah sure, could be a good example.

**Comment by ducin** [comment]
done in #24

**Comment by ducin** [comment]
thx!
