### ISSUE TITLE
Randexp generates some string with unicodes if use '\s' in regexp

### ISSUE THREAD

**Issue by onikiienko** [fent/randexp.js#25]
Regexp from you doc:
![Image of rexexp](http://image.prntscr.com/image/b9f9d69b70ed407abf31ef402fee8c07.png)
Results:
![Image of generated string](http://image.prntscr.com/image/f1229610a5c542aa8ea23214128fe555.png)

**Comment by fent** [comment]
Whatever that character is..

    > /\s/.test(' ')
    < true

From Wikipedia,

>Used for interword separation in Ogham text. Normally a vertical line in vertical text or a horizontal line in horizontal text, but may also be a blank space in "stemless" fonts. Requires an Ogham font.

**Comment by pft** [comment]
I was under the, admittedly wrong, impression that the `defaultRange` would restrict `\s` (and other such shorthand ranges) as well.

It would be very useful if there was an option for this.

**Comment by fent** [comment]
Ah, I see what you mean. `defaultRange` only restricts negated sets, since the characters included in a negated set can be vague, compared to a set that explicitly defines each character included.

I think this warrants additional opinions.

There could be an option added for this, like `defaultRange` but only for non-negated-sets. But I think we should first decide if to use `defaultRange` for both of these cases or not.

**Comment by pft** [comment]
I guess if a user (explicitly) sets a `defaultRange`, it is expected all all non-negated (shorthand) sets be in that range.

However this would of course introduce backwards-incompatible changes if users *did* expect the returned values to come from a larger range.

So perhaps we could use `defaultRange`, but only apply this logic if an extra option was on (`applyDefaultRangeToNonNegatedSets`?)

**Comment by xPaw** [comment]
This change doesn't seem to have been correct.

For example for a regex like `[12]`, you'd expect the range to be `1` (49 as int) or `2` (50 as int).

This does work with default range, but if you change it, for example like `r.defaultRange = new DRange( 64, 64 );`, then it won't intersect and the range will actually be empty.
