### ISSUE TITLE
are there any options to configure the max and min length of the random string generated

### ISSUE THREAD

**Issue by subeeshcbabu** [fent/randexp.js#26]
-  It would be really useful, if this can configure the result by providing  `maxLength` and `minLength` options.

**Comment by fent** [comment]
Tokens can be given a min/max count. I don't see how a min/max for the generated strings would make sense. If for example you give RandExp the empty but valid expression `//`, what would be generated with a `minLength`?

For `maxLength`, you could slice the returned string, if you don't want to set that through token repetitionals.

**Comment by fogine** [comment]
> If for example you give RandExp the empty but valid expression `//`, what would be generated with a `minLength`?  

That would be an error or same as `/.*/`  

`json-schema-faker`, which is using this library for generating values from json-schemas that define regex patterns, would really use the `minLength` option.

https://github.com/json-schema-faker/json-schema-faker/issues/486

As `json-schema` can define `minLength` for strings, eg:  

```javascript
{
    type: 'string',
    pattern: '^A[CD]{1,6}B$',
    minLength: 6
}
```

for the above schema `"ACDCDB"` is valid, however `"ACDCDCDB"` is not.
