### ISSUE TITLE
"Validations" support

### ISSUE THREAD

**Issue by cyrilchapon** [fent/randexp.js#32]
It would be very great to support "validations" (don't known the real word for this, I mean `(?=)` stuff).

It would allow one to use same regex to validate a password and to generate a random one.

Like this regex :

`^(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])$`

Ability to specify a separated string length (min ? max ?) would be very great too.

**Comment by cyrilchapon** [comment]
Hum. It seems to work, but not on the demo page. [This page](https://www.browserling.com/tools/text-from-regex) using the library showed me that.

**Comment by fent** [comment]
Dupe of #18 

You can specify min/max for repetitionals https://github.com/fent/randexp.js#infinite-repetitionals
