### ISSUE TITLE
please avoid using git url in semver

### ISSUE THREAD

**Issue by jchip** [fent/randexp.js#46]
Hi, we use enzyme for our internal projects.  Our internal build machines have very restricted access to the outside.  Since enzyme pulls a bunch of dependencies that eventually pulls this module, our build started failing since 0.4.7 was published with discontinuous-range semver changed to git url.

Can you publish your version of discontinuous-range under another name and update 0.4.x version please?

**Comment by vittoriozamboni** [comment]
+1, unfortunately we have the same issue and we cannot fetch github packages directly.
It would be awesome if you can drop it in favor of a published package.

**Comment by vittoriozamboni** [comment]
Thanks!

**Comment by ethanchiddicks** [comment]
Requesting we reopen this as the 0.4.7 version is still using a Git URL. Libraries that rely on randexp (eg. json-schema-faker) using ^0.4.X version specifier are still failing in build environments without Git installed.
