### ISSUE TITLE
please retro publish a 0.4.x version

### ISSUE THREAD

**Issue by jchip** [fent/randexp.js#48]
Thanks for the fix for https://github.com/fent/randexp.js/issues/46

We still have the problem we encountered because the fix was published to 0.5.x line only, but the dependencies we use are still pulling version 0.4.x.

Could you retroactively apply the fix to 0.4.x line and publish a version on that please?

**Comment by fent** [comment]
Closed via above branch

**Comment by jchip** [comment]
thank you
