### ISSUE TITLE
If used in a React project, causes a build fail

### ISSUE THREAD

**Issue by storrisi** [fent/randexp.js#55]
This is the error that i cought during the building process of a React app where i used this library:

```
Failed to minify the code from this file: 
./node_modules/randexp/node_modules/ret/lib/sets.js:3
```

**Comment by fent** [comment]
Does your minifier support es5?

**Comment by storrisi** [comment]
@fent i'm using webpack, i assume it needs a specific configuration to handle this

**Comment by fent** [comment]
Maybe babel

**Comment by storrisi** [comment]
@fent is already configured

**Comment by fent** [comment]
Then, I don't know, might be ordering the config incorrectly or not configuring babel for it?

Just guessing all this based on `sets.js` line 3 containing an arrow function, an es5 feature

**Comment by storrisi** [comment]
I'm developing on React based on ES6 specs, so arrow functions are almost complained

**Comment by fent** [comment]
Closing, since this is related to minifying in a build config, and not randexp.;

**Comment by maurusrv** [comment]
hi @fent, i got this same error while building, may i ask if you fixed it and how? thank you!
