### ISSUE TITLE
release versions mixed up in npm registry

### ISSUE THREAD

**Issue by EntropyAu** [fent/randexp.js#56]
The releases appear mixed up in the NPM registry - https://www.npmjs.com/package/randexp
It's unclear whether 0.4.9 or 0.5.2 are the latest versions. Would you mind confirming? Many thanks!

Current Tags 
0.4.9 latest

Version History 
0.4.9 2 months ago
0.5.2 2 months ago 
0.4.8 2 months ago
0.5.1 2 months ago
0.5.0 2 months ago
0.4.7 2 months ago

**Comment by fent** [comment]
0.5.2 is the latest version. But if for some reason you're still stuck on 0.4.x, like on https://github.com/fent/randexp.js/issues/48, then use that version
