### ISSUE TITLE
Comparing 2 regex if they can match same string

### ISSUE THREAD

**Issue by amitguptagwl** [fent/randexp.js#57]
I've a use case when I want to compare 2 regex to check if they can match same string. Eg.

```js
var regex1 = "my age is [0-9]+";
var regex2 = "my age is [0-9]{1,3}";
```

Is it possible to do such comparison with this library?

**Comment by fent** [comment]
No, but look at https://github.com/fent/ret.js

**Comment by fent** [comment]
I don't think that'll work for every regex. For example, `a` and `[ab]`

**Comment by amitguptagwl** [comment]
For this example random string would be `a`, and `a`. Both are matching it means both regex can have common string.

**Comment by fent** [comment]
Or it could sometimes be `a` and `b`

**Comment by fent** [comment]
I see. Missed the `randInt` function
