### ISSUE TITLE
A mistakes

### ISSUE THREAD

**Issue by likyh** [fent/randexp.js#70]
![image](https://user-images.githubusercontent.com/3294100/61543843-d224ca00-aa76-11e9-9bb5-3326f16d2a30.png)
```typescript
import RandExp from "randexp";
const randexp = new RandExp(/[23456789QWERTYUPASDFGHJKZXCVBNM]{6}/);
randexp.gen();
```
needn't `* as `

**Comment by fent** [comment]
@littlepiggy03 since you made the changes to add typings, what's your take on this?

**Comment by littlepiggy03** [comment]
@likyh It depends on your development environment. If you are using `typescript@>2.7` and `"esModuleInterop": true` in is `tsconfig.json`, omit `* as` could be omitted.

**Comment by fent** [comment]
hmm, let's leave it for now then.
