### ISSUE TITLE
gen() generate empty string while there's a match

### ISSUE THREAD

**Issue by rachedanis** [fent/randexp.js#86]
Hello, I'm using "randexp": "^0.5.3" with node 8.
I'm trying to generate a string that respect two regexes r1 and r2, so I've made a regex and operator (?=r1)(?=r2) but the gen() always generates empty string.

My example : 
```
const r1 = 'TEST';
const r2 = 'TEST';
const random = new RandExp(new RegExp(`(?=${r1})(?=${r2})`)).gen() // expecting TEST but was ""
```

**Comment by fent** [comment]
Lookaheads don't generate anything, currently

https://github.com/fent/randexp.js/issues/18
